/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package deltix.web.client;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class WebClientTestTest {
    @Test void appHasAGreeting() {
    }
}
